name: Deployment

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@master

    - name: git config
      env:
        USER_NAME: ${{ github.event.pusher.name }}
        USER_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config --global user.email "$USER_EMAIL"
        git config --global user.name "$USER_NAME"
    - name: make deploy keys
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: clone static_site_repo
      run: |
        cd ..
        git clone https://github.com/exqt/exqt.github.io static_site_repo
    - name: install dependencies & build
      run: |
        yarn
        yarn build
    - name: move build files to static files repo
      run: |
        mv ./dist/* ../static_site_repo/pixel-font-maker
    - name: push changed files
      run: |
        cd ../static_site_repo
        git add .
        git commit -m "Update pixel font maker"
        git push origin master
